spring:
  application:
    name: user-reactive-service
  r2dbc:
    url: r2dbc:h2:mem:///user-db
    username: user
    password: password
  sql:
    init:
      mode: embedded

server:
  error:
    include-binding-errors: always
    include-message: always

jwt:
  token:
    secret: dv7m9eFK6x0aJXkM4Nxk7aG5ryncn04y7vSEdHHfDBWuPQM6CnDwpzBZbEBfhb5A

# enables debug logging for the H2 R2DBC driver

logging:
  level:
    io.r2dbc.h2: DEBUG

# SQL logging can also be enabled by adding below configuration property: logging.level.org.springframework.r2dbc=DEBUG
# This property enables debug logging for Spring's R2DBC operations. It provides information about Spring's R2DBC infrastructure.
# The org.springframework.r2dbc logger is more general and covers Spring's R2DBC operations across different database implementations,
# while io.r2dbc.h2 is specific to the H2 database driver.

#logging:
#  level:
#    org.springframework.r2dbc: DEBUG