spring:
  application:
    name: user-reactive-service
  r2dbc:
    url: r2dbc:h2:mem:///user-db
    username: user
    password: password
  sql:
    init:
      mode: embedded

server:
  error:
    include-binding-errors: always
    include-message: always